### ISSUE TITLE
V1 Roadmap

### ISSUE THREAD

**Issue by 2nthony** [evillt/docute-demo-code#1]
## Features

- [ ] Toggle to show code
- [ ] `Try it!` which mean it's try online via codepen or other else
- [ ] One-click to copy code
- [x] Support pure CSS(`<v-style>` based)
- [x] Add border for living demo(need to improve)
